-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 23, 2018 at 11:45 AM
-- Server version: 10.1.26-MariaDB
-- PHP Version: 7.1.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `radiant-dusk-89811`
--

-- --------------------------------------------------------

--
-- Table structure for table `movieinfo`
--

CREATE TABLE `movieinfo` (
  `movieId` varchar(11) NOT NULL,
  `description` varchar(300) NOT NULL,
  `review` varchar(3000) NOT NULL,
  `rating` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `movieinfo`
--

INSERT INTO `movieinfo` (`movieId`, `description`, `review`, `rating`) VALUES
('tt0060196', 'When you have to shoot, shoot. Don\'t talk!', '<br>Sergio Leone\'s The Good, the Bad and the Ugly is one heck of a movie to remember for a long time (in general, for person\'s life span!). The background score by Ennio Morricone, will leave you humming it all day and the Western world created by Leone will make you wish to be a cowboy! The film, though made in the mid 1960\'s still possesses an unmatched technical excellence, the cinematography, the art direction, the acting, everything is just perfect!<br>\r\n\r\n<br>You will certainly fall for Clint Eastwood\'s awesomeness and Eli Wallach\'s slavishness which always brings out a humor to every bit of the film. Though a western adventure film, it still manages to unveil America\'s dark past, the Civil War, in a very unique Sergio kind of a way. And yet it is artistic enough to appreciate it\'s beauty. The screenplay is way too good and the performances are a new upper bound. This film has always been a childhood partner for everyone (if not all, almost all). It is a rare piece of cinema which inspired many to make such kind of films, always in a will to reach it but every time way too far.<br>\r\n\r\n<br>Every bit of it is enjoyable and it is a must watch especially for the newbies. I\'m signing off with a 90% score for this film. It\'s a treat guys, trust me!<br>', 90),
('tt0068646', 'An Offer you can\'t refuse!', '<br>If cinema is a religion, then Fracis Ford Coppola\'s The Godfather (the series) may be viewed as a cathedral. Not to offend anyone, I just wanted to convey it\'s grandness in the world of movies. Almost all of the modern crime - dramas are more or less inspired from this epic. With cult status, great acting performances, and a great storyline from the mafia genre master Mario Puzzo, this adapted screenplay is one to be kept in a museum.<br>\r\n\r\n<br>The film revolves around the protagonist cum antagonist Michael Corleone (played by Al Pacino), and his powerful family in New York City in the mid 1940\'s just after the World War II had finished. Michael\'s father Vito Corleone (played by Marlon Brando), currently the head of the Corleone family, somehow gets into some trouble and situations turn up that way that Michael, who in the first place never wanted his hands to get dirty, gets into this family stuff. Things get creepy, and the story gets more complex as we move forward.<br>\r\n\r\n<br>The film received three Oscars, Best Picture, Best Actor (Marlon Brando), and Best Adapted Screenplay (Mario Puzzo and Francis Ford Coppola). I feel that the Best Director Oscar should have gone to Francis Ford Coppola, as he deserved it in every sense. Extremely amazing performances from Marlon Brando, Al Pacino and Robert DuVall (played the character of Tom Hagen, my personal \'all - time\' favorite).<br>\r\n\r\n<br>For all the Hollywood classic lovers this is a must watch, even the youth will like this epic. It\'s slow at some points but at the end every thing is justified, because Coppola made you an offer you can\'t refuse! I\'m gonna go with 88% for this classic.<br>', 88),
('tt0071562', 'Keep your friends close, but enemies closer!', '<br>I\'ll tell you my personal experience for my love for cinema, the reason behind it all is this film! This is one review I took the most time to write, because I was literally blown away by this film. It is simple yet complex, slow paced yet deeply moving, forward yet backward, plain yet smart, and crime drama yet art! The screenplay is one of the best I\'ve witnessed ever. I believe this was Al Pacino\'s best acting performance ever throughout his career. The film won six Oscars including Best Picture (became the first film series (duology) to win Best Picture Oscar for both the films), Best Director (this time Coppola nailed it!), Best Screenplay (again!), Best Music, Original Score (it will literally blow you with its mightiness), and Best Supporting Actor (Robert De Niro just killed it all, and that too in Italian (became the first actor to win an Oscar for a performance in a foreign language)).<br>\r\n\r\n<br>A complex narration between the lives and time lines of Vito Corleone\'s early days in New York and Michael Corleone\'s empire in the New York City and many major parts America of the 1950\'s. With it\'s ultimate art at the end it comes very near to my heart. I even liked it more that its much hyped first part.<br>\r\n\r\n<br>All and all, a great collection to watch based on the cult novel with the same title by Mario Puzzo, this film is a gem. I\'ve not seen such a film, and I don\'t want you even to miss it. It\'s a real pleasure, and I\'m giving it a 91% score from my end.<br>', 91),
('tt0109830', 'Life is like a box of chocolates. You never know what you\'re gonna get!', '<br>This is a gigantic epic in my and almost everyone\'s perspective, whether aged or young, girl or boy, everyone just loves Forrest Gump! If you miss this one, you really missed the best of movies. This certainly is the best picture of 1994 even after competing with giants like The Shawshank Redemption, The Lion King and Pulp Fiction, and suitably won Oscars for Best Picture, Best Director (Robert Zemeckis), Best Actor (Tom Hanks), Best Adapted Screenplay (Eric Roth), Best Film Editing and Best Visual Effects (they were so seamless that you won\'t believe they were there in the film, and that\'s the beauty!).<br>\r\n\r\n<br>This is the story of a mentally retard, low IQ person, Forrest Gump, and world from his point of view, shown so innocently and adorably. I can bet it can cheer you up from any mood, and you\'re gonna spread happiness by recommending this once you experience it yourself! His life journey is shown from his own perspective and is so humorous that you won\'t be able to control your laughter, every bit of it! And, yet it very smartly portrays the real life challenges that everyone faces and the attitude that one must possess to tackle problems. Goodness and Innocence are not just two terms found in books, they should be prominent enough to be noticed.<br>\r\n\r\n<br>This film is, if I sum it up, a real gem which I don\'t think can ever be found again. This film is my love and will always be and I can bet you if you see it, you\'re gonna feel the same. A must must watch for everyone, I would rather say \"An N time watch\"! I\'ll give it 94% score and stop myself from writing any further, because I know I won\'t stop.<br>', 94),
('tt0110912', 'The path of the righteous man!', '<br>In my perspective, 1994 was a year to remember for movie buffs like us. First of all it gave us Forrest Gump, The Shawshank Redemption, The Lion King, and finally this young independent \"new generation\" awesome \"Quentin Tarantino\" trademark film - Pulp Fiction. This is film is, if I just had one word to describe, \"Cooool!\". Well, and second, it marked the arrival of a new kind of cinema into the industry with an overwhelming response. Quentin Tarantino marked his arrival as well and since then there\'s no turning back.<br>\r\n\r\n<br>The style adapted by his films have always been unique - modern, savage life, though filled with a lot of violence, filthy mouths, and no soft corners. This is the way America has progressed throughout, and his films are a nearly correct portrayal. The story is based on two mobsters who face a sequence of events on a job one fine day, that ultimately their perspectives get affected by what they do (not necessary for all, cause it\'s Tarantino guys!).<br>\r\n\r\n<br>It is both witty and humorous in its own ways. String performances by Samuel L. Jackson, John Travolta, Uma Thurman, Tim Roth and Harvey Keitel (though he had a cameo but still he was awesome!). The film righteously won an Oscar for Best Original Screenplay (Roger Avary and Quentin Tarantino) and Palme d\'Or at Cannes Film Festival. It is a delightful watch especially for the youth. I\'m giving it 81% because of its memorable nature and spellbound portrayals and expressions.<br>', 81),
('tt0111161', 'Hope is a great thing!', '<br>The Shawshank Redemption is based on the classic short story \'Rita Hayworth and Shawshank Redemption\' by the great writer Stephen King, who has not only proved his worth in storytelling but has also given the Hollywood industry some great classics like Stanley Kubrick\'s, The Shining (1980), and Rob Reiner\'s Stand By Me (1986) over the past few decades. Let\'s just talk about Frank Darabont\'s direction, if I had to in one word it\'s awesome! A deeply moving piece of cinema, which is rare to find. Literally, you don\'t get to see such films even in two decades. A fantastic portrayal of a prisoner by Morgan Freeman makes him earn an Academy Award nomination. All in all, the film received seven Oscar nominations, including Best Picture, Best Direction and Best Actor. Believe me guys, I don\'t like wasting people\'s time, but this gem, if you trust me, is worth investing your precious time. I know you\'re not gonna regret this humble yet thrilling experience, which not only portrays the story of a few prisoners and jail staff member, but teaches you many important things about life, most importantly, about \'Hope\'.<br>\r\n\r\n<br>The story revolves around the protagonist Andy Dufrense, who is charged for murdering his own wife, but is he really guilty? You\'re gonna find out in the movie. The jail sequences in New England gives you a stunning experience of a real mid 1940\'s jail in the United States of America.<br>\r\n\r\n<br>This film really moved me with its stunning end sequence and this character build throughout. For such a lovely portrayal of such a beautiful storyline amazes me every time I watch it. The cast ensemble is quite fantastic and the characters are pretty believable in this fictional plot. For such a rare and heart touching of art, I\'m gonna remember this for long, maybe till my last breath. I\'m gonna go with an 89% score for this one. It\'s a must watch guys, do watch it.<br>', 89),
('tt0137523', 'God Damn! We just had a near-life experience, fellas!', '<br>What to say about David Fincher\'s Fight Club, it speaks for itself. David Fincher has been one director who has always inspired me with his unique style of film making. He always brings out something shown in such a way you can\'t expect it to be shown. This film\'s USP is the character Tyler Durden (awesomely portrayed by Brad Pitt), who loves vandalism, hates the orthodox methods of living, and sees everything his way, which any one of us even in their wildest of dreams can\'t even imagine of thinking! Literally, once you see it you\'ll get to know this.<br>\r\n\r\n<br>The movie is quite humorous in its own ways, if you got the point of all the events narrated in a very complex and non - linear and non - traditional David Fincher fashion. The film is filled heaps of Tyler Philosophy which you are gonna appreciate as soon as you get it. The key is the style here. With some great performances from Brad Pitt, Edward Norton, Jared Leto and Helena Bonham Carter, Fight Club is not only a modern epic but it is a fictional theory which everyone (especially the youth) would want to live their lives like.<br>\r\n\r\n<br>A must watch, especially if you low or cheated. An all time favorite goes with an 86% score.<br>', 86),
('tt2582802', 'There are no two words in the English language more harmful than \"Good Job\"!', '<br>This film, Whiplash, marks the entry of a giant into the industry, Damien Chazelle, the director of this film. It shows you a lot of philosophy about life, show how hard it is to be successful and earn a name, that success no piece of cake.<br>\r\n\r\n<br>It deals with the life of a young boy, Andrew Neimann, an aspiring drummer artist, and his teacher, Terence Fletcher. It is portrayed so beautifully, that you will be spellbound, I was! Great performance by J.K. Simmons as Fletcher, which ultimately fetched him an Oscar for Best Actor in a Supporting Role! The film won three Oscars in all, for Film Editing and Sound Mixing and Supporting Actor.<br>\r\n\r\n<br>So simply it tells you that no one is good enough and to become one, you need a lot of dedication. That yes, there will be pot holes in your way, but you\'re not gonna stop. Even if you bleed, you won\'t stop. Till you get there! Even Miles Teller\'s portrayal of Andrew is amazing. It shows how much your parents care for you whether you know it or not, whether they show you or not, and whether you appreciate them or not!<br>\r\n\r\n<br>This review is progressing in a manner that the film is an emotional drama, no it\'s not! It is a hard slap on the faces of all those who think they are only one\'s who\'re gonna get successful. I recommend everyone to watch this film, as it is really a masterpiece in all sense. I\'m giving it a 92% movie score, cause it ain\'t worth less than that, believe me!<br>', 92);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movieinfo`
--
ALTER TABLE `movieinfo`
  ADD PRIMARY KEY (`movieId`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
